### ISSUE TITLE
[Page company] - Distribution of profits vs employees 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#10]
1) Il manque l'année sur ce graphique
<img width="1273" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/6a7bc76e-52e7-41bd-a0ed-6bf051253796">

2) le graphique de droite est manquant
<img width="478" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/f21d03bf-70ca-4242-8cf2-960d5eff8001">

**Comment by anquetos** [comment]
Année corrigée et graphique de droite ajouté.
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/8e0e63bd-e90e-425e-8269-f6614ff63d85)
