### ISSUE TITLE
[Footer] - liens non clickables

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#12]
liens non clickables 
<img width="667" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/0ffff3c4-964b-4a14-a4c9-bf03e7d3122d">

**Comment by anquetos** [comment]
Les liens sur les logos website, Twitter et LinkedIn sont ajoutés.
