### ISSUE TITLE
[Page download data]

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#14]
A ajouter

**Comment by anquetos** [comment]
Page ajoutée :
- j'ai mis une petite flèche dans le menu à la place de réécrire "download" ;
- le fichier se télécharge en csv ;
- son nom par défaut est "data_final_dataviz.csv".

![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/d48e61d1-293e-4455-bc88-4bdbb50add4d)
