### ISSUE TITLE
[Page company] - décomposer le score sur 100 plutot que pourcentage

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#22]
<img width="900" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/322c2ae7-7db4-4a82-a221-00a3e3972571">

**Comment by anquetos** [comment]
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/5ab90828-c1e1-4d56-bc83-9050ec172e78)
