### ISSUE TITLE
[Page Company] Affichage key metrics

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory_datavize#24]
Dans l'affichage des key metrics:

- enlever heaqdquarter, on l'a deja en haut
-enlever année (1 row)
-si les variables son NA mettre NA et pas 0 ( par example on a un souci avec profit before tax)
-rename "index" = "variable" et "0" = "value"
-rename la box "Key metrics" = "Company size"

![Screenshot 2024-05-27 at 22 41 30](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/b66d72bd-83bf-4c90-abf5-54b23a138646)
![Screenshot 2024-05-27 at 22 41 46](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/aabcb214-ed04-4eae-8a97-04040bf9448b)

**Comment by anquetos** [comment]
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/232b0d43-59f1-4b4f-9b44-96b7e75a4cbf)
