### ISSUE TITLE
[Home page] improve charts with reports count

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory_datavize#25]
Est ce que tu peux améliorer ce graphique? 

- afficher tout les annees
- changer le titre du y axis en "number of reports"
- remove le titre du x axis "year"

le mieux ça serait d'imiter le style du graph en PJ si possible

![Screenshot 2024-05-27 at 22 46 10](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/d15ce955-e779-449e-84e6-efb0fe569132)
![Screenshot 2024-05-28 at 09 53 25](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/caa3de9f-777a-4375-8f2e-87d49c454ccb)

**Comment by anquetos** [comment]
Reste un petit soucis de positionnement mais sinon c'est ok. J'ai repris le style de Darlène sur Figma.
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/d066fed9-3ccc-48aa-997e-ddb65f954f54)
