### ISSUE TITLE
[Home page] graph with company names

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory_datavize#26]
![Screenshot 2024-05-27 at 22 46 22](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/85900696-e5f9-4c43-b8d5-5ba73b79c733)

Si possible améliorer le graph:

- enlever les axes
- le rendre un peu plus grand
- et mettre en hover une variable (genre nom de l'entreprise et headquarter) ou rien.

**Comment by anquetos** [comment]
J'étais en train de travailler dessus.

![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/91d3a4d1-f1e2-4e2f-b6af-c15f9a37ac87)
