### ISSUE TITLE
[Home Page] change text blue box 

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory_datavize#27]
![Screenshot 2024-05-27 at 22 45 22](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/255be889-ee40-42ef-baf5-e9b8d3acf9f9)

on peut remplacer avec 
The Call for Tax Transparency 

Investors, activists, and governments demand transparency - are corporations paying their fair share? But too often, the data trail goes cold. Country-by-Country Reporting makes corporate tax strategies more transparent, one company at a time.

**Comment by giuali** [comment]
Tu peux aussi changer le titre "And there are a lot of stories to tell" avec " Why this project?"

**Comment by anquetos** [comment]
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/239f6496-9bb3-4c2f-ae30-afbb654d58ea)
