### ISSUE TITLE
[Page Company] - Remplacer Cbc par Country by Country dans le titre

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#3]
Sur les deux bulles ici - remplacer Cbc par Country by Country dans le titre

<img width="620" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/f3214c99-4af1-4230-9324-4f0865babc3a">

Dans la deuxième bulle : 
- idéalement ajouter une barre en dessous du chiffre "/100" (car la note est sur 100) - dégradé de vert (pour 100) vers rouge 0.
- si pas possible ajouter "(over 100 - 100 being the best grade)" dans le titre de la bulle.

**Comment by anquetos** [comment]
Pour le remplacement de Cbc, ne peut-on pas ajouter une astérisques et écrire dessous ce que cela signifie ?
Le soucis c'est que le texte devient un peu trop long pour les pavés blancs donc à par diminuer la police...
![image](https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/123625107/11eaf63a-6530-4e71-b126-1893435e51c9)

**Comment by anquetos** [comment]
Pour la deuxième bulle, il était prévu que le score soit affiché en pourcentage on reste là-dessus où on part sur /100 ?

**Comment by anquetos** [comment]
- Calcul corrigé.
- Affiche de "/100" dans la bulle.
- Titres corrigés.

![image](https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/123625107/81993a1d-845b-4989-b9ba-2db69d57a867)
