### ISSUE TITLE
[Company Page] data calculations for revenues chart

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory_datavize#39]
![Screenshot 2024-06-01 at 14 55 39](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/94c9d513-7be0-4f22-9e5b-ca6d12efb241)
![Screenshot 2024-06-01 at 15 00 42](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/103266974/faf16bc2-f863-421f-94a6-528702ad88ea)

Dans ce graphique on aggrege dans une grand categorie "others" les info qui ne sont pas dans le top 10. ça peut etre trompeur, est ce que on peut soit:
montrer que le top 10 ( et changer le titre en " Revenues in top 10 countries"
faire un graphique deroulant comme pour profit vs employees avec une barre sur le coté.

voir l'option plus faisable en fonction du temps

**Comment by anquetos** [comment]
Graphique déroulant.
