### ISSUE TITLE
[Page company] - Erreur Graph "CbC Transparency Grade average over all reports"

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#4]
Erreur sur le graphique

La valeur du quatrième carré - est fausse : 
Pour shell cela vaut actuellement 4 alors que cela devrait valoir 100

<img width="323" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/ee4cd336-267d-4d92-8ef7-cedd7d1bfcf3">

**Comment by anquetos** [comment]
- Caclul et mise à jour valeur corrigée.

![image](https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/123625107/6f51df6c-aa0d-4e19-8fc8-86f2df6988cc)
