### ISSUE TITLE
[Company page] % profit and profit / employee by country - incohérence entre labels et légende

### ISSUE THREAD

**Issue by Pagehey** [dataforgoodfr/12_taxobservatory_datavize#44]
Hello ! 👋 

Je decouvre le site avec le lancement officiel et j'ai l'impression qu'il y a des incohérences sur un des charts (_% profit and profit / employee by country)_.

Au hover, le label ne correspond pas forcément à la légende (ici sur la page de TotalEnergies pour l'année 2021, mais constaté pour d'autre compagnies aussi)

Je n'ai pas participé au projet mais je me suis permis d'ouvrir une issue directement ici plutôt que passer par le slack, et je n'ai pas vu d'autre issue sur ce sujet, est-ce que c'est la bonne procédure ?

<img width="614" alt="Capture d’écran 2024-06-06 à 11 40 11" src="https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/39967933/e8e354f4-d705-4f8f-a0ae-e0a09950ed6f">
<img width="614" alt="Capture d’écran 2024-06-06 à 11 40 06" src="https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/39967933/85d7d273-7bde-4626-830f-58a49d42dfc4">

**Comment by jeremyfix** [comment]
Oui, vous avez très bien fait de notifier ce bug sur le github plutôt que le slack !  Merci pour ce rapport de bug.

**Comment by anquetos** [comment]
This has been corrected in commit https://github.com/dataforgoodfr/12_taxobservatory_dataviz/commit/4f8b97992f5422f39576c02a7ead697de2e07ff6 but it is not deployed to production.
