### ISSUE TITLE
[Company page] Tax haven / non taxen mismatch label  ?

### ISSUE THREAD

**Issue by jeremyfix** [dataforgoodfr/12_taxobservatory_datavize#48]
When overing a blue dot on the "% profit and profit / employee by country" visualization ,the label appears as the "country - Non tax haven" although the dot is blue and labeled tax haven;

For example, for shell, if you over the mouse on Spain, the blue dot around 7%,  in the blue box, it is written " Spain - Non tax haven" and, aside the box, it is wirten "Tax haven" ; Is the "Non tax haven" in the box incorrect ? 

For the gray boxes, it is written both inside the box and aside the box : "Non tax haven"

![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/1128418/ae2f1c98-85a8-4986-b49d-e075f8a0c8e1)

**Comment by anquetos** [comment]
This has been corrected in commit 4f8b979 from yesterday but it is not deployed to production.
See for example Netherlands.
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/a5a25687-c49e-44d8-9c2a-b49363c3c31a)
