### ISSUE TITLE
[Page contact Form] - contact form missing

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#5]
Le contact form est manquant 

ne pas perdre de temps dessus - sinon simplement mettre une adresse mail : 
<img width="253" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/41eb4782-3928-4702-8919-922c3db8c440">

<img width="1152" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/b54d173c-6c80-4a4f-ace1-efa0355a2c53">

**Comment by anquetos** [comment]
J'ai mis une enveloppe avec lien hypertexte à la place du form.
![image](https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/123625107/30da91d3-5907-46ae-ba23-78310578310c)
