### ISSUE TITLE
Front - Performance / Intégration / Accessibilité / SEO

### ISSUE THREAD

**Issue by RiwsPy** [dataforgoodfr/12_taxobservatory_datavize#55]
On a pas ~~facilement~~ la main mais il y a des axes d'amélioration.

* Performance : **10Mo** de chargement pour la page d'accueil (??!)
  * Taipy : 7Mo
    * ~~des packages optionnels ?~~ (déjà fusionné : c'est tout ou rien, déjà minifié)
    * ~~defer~~ (déjà en place)
    * ~~fusionner les feuilles de style ?~~ (rien de prévu)
    * trouver des solutions…
  * Réduire le poids des images : 2.5Mo
    * https://github.com/dataforgoodfr/12_taxobservatory_dataviz/pull/45
* Intégration
  * Nettoyer les feuilles de style du projet
  * Intégrer directement les fonts dans le projet au lieu d'aller chercher chez fonts.googleapis.com
  * Utiliser des variables (notamment pour les fonts et les couleurs)
  * ~~Pas une bonne pratique que de pouvoir overrider les feuilles de style depuis des fichiers python (stylekit)~~ (nécessite trop de temps)
* Accessibilité
  * Mettre des balises alt aux images + height/width quand possible
* SEO
  * ~~Ajouter les balises meta~~ (rien de prévu, on oublie)

**Comment by gaudinnicolas** [comment]
Penser à merger la PR 45 qui traite une partie du sujet.

**Comment by anquetos** [comment]
Quelques remarques :
* Fusion et surtout nettoyage des feuilles de styles prévue de mon côté. Il y a pas mal de classes qui sont obsolètes et non utilisées.
* Pour le stylekit c'est [la méthode indiquée par Taipy](https://docs.taipy.io/en/latest/manuals/gui/styling/#style-sheets) qui avait été suivie. Tu penses qu'il y a moyen de faire autrement ?
* Concernant les balises images, les pages ont été créées avec la classe Mardown de Taipy, du coup c'est un peu limitant pour pas mal de chose. Mais je vois qu'il y a une propriété `label` sur [l'élément image](https://docs.taipy.io/en/latest/manuals/gui/viselements/image/). Tu penses que ça peut suffire ?
* Pour le SEO et les balises meta, avec la méthode du Markdown j'aurais tendance à dire que ça va être compliqué.

**Comment by RiwsPy** [comment]
* Pour les feuilles de style c'est plutôt les leurs qui posent problème (il y en a beaucoup et elles sont appelées une à une). Cela dit, un brin de ménage sur celles du projet est une bonne idée.
* Pour le stylekit, je sais que ce qui a été fait est conforme à la doc. C'est quand même une mauvaise pratique de leur part, on override pas le front depuis le back et inversement. J'ai creusé un peu. Visiblement rien n'est prévu pour faire fonctionner taipy autrement que comme eux l'on prévu. Il y a du inline !important un peu partout et pas de moyen de changer l'ordre d'appel des feuilles de style sauf à réécrire toutes les méthodes : c'est un enfer.
* `label` va ajouter un tag `aria-label` c'est toujours ça de pris. Il y a des balises `<a>` sans alt tout de même, par exemple le logo de D4G.
* Effectivement, rien n'est prévu pour les balises meta et rien n'est prévu pour overrider leurs fichiers html…

Les marges de manœuvre sont donc plus que très réduites. Je mets à jour le ticket.


edit : s'il est compliqué de passer outre le stylekit, celui-ci défini tout de même des variables utilisables dans le css.
```py
stylekit = {
  "color_primary": "#021978"
}
```
va créer 
```css
:root {
  --color-primary: #021978;
}
```
(note le `_` qui est devenu `-`)

et le rend utilisable dans toutes les feuilles de style :
```css
  background-color: var(--primary-color);
```
