### ISSUE TITLE
[Page Company] - Tax transparency section

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#6]
Les deux graphiques sont faux : 

<img width="1219" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/b8685a11-4997-4d2a-a778-00b27eb8cf21">

1) Le premier devrait être une note sur 100
Pour Shell devrait valoir 100 pour l'année 2020. 

2) Le deuxième graphique est manquant 
- cela devrait ressembler à ca : 
<img width="602" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/fd854e23-f064-41b0-98b0-76042f003a96">

- enlever le (tbd) qui veut dire to be discussed et qui est faux.

**Comment by anquetos** [comment]
![image](https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/123625107/58e2d062-aee1-4736-ab3a-4d9f811066c0)
