### ISSUE TITLE
[Page Company] - erreur graphique Key metrics

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_taxobservatory_datavize#8]
erreur graphique Key metrics : 
<img width="514" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/265b1d24-9c46-44ad-93f3-5fa02b952263">

Il manque les données statiques du tableau. Cela devrait ressembler à ca : 

<img width="264" alt="image" src="https://github.com/dataforgoodfr/12_taxobservatory_datavize/assets/35841420/4cc7feaf-cbcd-400c-b0da-6eb1a2d90ded">

**Comment by anquetos** [comment]
Les données changent quand on change la société ou l'année.
Les données statiques apparaissent.
![image](https://github.com/dataforgoodfr/12_taxobservatory_dataviz/assets/123625107/0934e278-6227-42c2-9695-61aa47a89fb2)
